### ISSUE TITLE
Environment variables in docker-compose

### ISSUE THREAD

**Issue by supermoriarty** [Dispersia/Dotnet-Watch-Docker-Example#1]
With this solution it seems like the dotnet app does not run with the docker-compose enviroment settings. This makes sense since the code is just mounted in the image, but is there a way around this?

**Comment by Dispersia** [comment]
It's actually dotnet watch run that doesn't pass it down. There is a way to do it, but I'm at work and can't remember off the top of my head. You can look at https://github.com/aspnet/DotNetTools/blob/master/src/dotnet-watch/DotNetWatcher.cs#L65 to get an idea, but I need to follow it on an actual computer to give a completely accurate answer :)

**Comment by supermoriarty** [comment]
Ah of course, didn't actually think about it being dotnet watch run that couldn't do it, I just assumed that it was something with my docker environment.

Solved it by mounting a env-file into app/settings and then in Program loading an optional configuration file from /settings

Thanks!
